config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'directories#index'

  resources :directories
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/directory.rb
class Directory < ApplicationRecord
  has_many :notes
  has_many  :descendents, class_name: 'DirectoryPosition', foreign_key: :parent_id
  has_many  :ancestors, -> { joins(:parent).where.not(level: 0).order(level: :desc) }, class_name: 'DirectoryPosition', foreign_key: :child_id
  belongs_to  :parent, class_name: 'Directory', optional: true

  after_create  :update_self_position
  after_create  :update_position

  def full_path
    self.ancestors.pluck("name").join('/') + "/#{self.name}"
  end

  def update_self_position
    DirectoryPosition.create(parent_id: self.id, child_id: self.id, level: 0) 
  end

  def update_position
    query = ActiveRecord::Base.sanitize_sql(["INSERT INTO directory_positions(parent_id, child_id, level)
      SELECT p.parent_id, c.child_id, p.level+c.level+1
      FROM directory_positions p, directory_positions c
      WHERE p.child_id=? AND c.parent_id=?", self.parent_id ,self.id])

    DirectoryPosition.connection.execute(query)
  end
end

app/models/directory_position.rb
class DirectoryPosition < ApplicationRecord
  belongs_to  :parent, class_name: 'Directory'
  belongs_to  :child, class_name: 'Directory'


  
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to  :directory, optional: true

  scope :search, ->(param) { includes(:directory).where("name LIKE ?", ["%#{param}%"]) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  # for brevities sake, just throwing it all in a single controller/view


  def index
    @current_directory = Directory.find_by(id: index_params[:current_id])

    parent_id = @current_directory.present? ? @current_directory.id : 0

    @directories = Directory.where(parent_id: parent_id)
    @directories.where(parent_id: parent_id).where("name ILIKE ?", "%#{index_params[:search_term]}%") if index_params[:search_term]

    @directory = Directory.new(parent_id: parent_id)

    @note = Note.new(directory_id: parent_id)
    @notes = Note.where(directory_id: parent_id)

    @search_results = Note.search(index_params[:note_search_term]) if index_params[:note_search_term]
  end

  def create
    directory = Directory.create(directory_params)
    redirect_to action: :index, current_id: directory.parent_id
    # redirect_to :back
  end

  private
    def directory_params
      params.require(:directory).permit(:name, :parent_id, :child_id)
    end

    def index_params
      params.permit(:parent_id, :child_id, :current_id, :note_search_term)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    note = Note.create(note_params)
    redirect_to controller: 'directories', action: :index, current_id: note.directory_id
  end

  private
    def note_params
      params.require(:note).permit(:name, :directory_id, :note_text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directories/index.html.erb
<%# # for brevities sake, just throwing it all in a single controller/view %>
<h1><%= link_to "Directories", directories_path() %></h1>
<% if @current_directory.present? %>
  <h3><%= link_to "UP", directories_path(current_id: @current_directory.parent_id ) %></h3>
  <h3><%= @current_directory.full_path %></h3>
<% else %>
  <h3>Top</h3>
<% end %>

<% @directories.each do |d| %>
  <p> <%= d.id %> <%= d.name %> <%= link_to "#{d.name}", directories_path(current_id: d.id) %> </p>
<% end %>

<br>
<br>
<h3>notes</h3>
<% @notes.each do |n| %>
  <p> <%= n.id %> <%= n.name %> </p>
<% end %>

<br>
<br>
<h3>Create folder in current dir</h3>
<%= form_for @directory, url: {action: "create"} do |f| %>
  <%= f.text_field :name %>
  <%= f.hidden_field :parent_id, value: @directory.parent_id %>
  <%= f.submit "Create Directory" %>
<% end %>

<br>
<br>
<h3>Create note in current dir</h3>
<%= form_for @note, url: notes_path(@note) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :note_text %>
  <%= f.hidden_field :directory_id, value: @current_directory.present? ? @current_directory.id : nil %>
  <%= f.submit "Create Note" %>
<% end %>

<br>
<br>
<h3>Search</h3>
<%= form_tag directories_path(), method: 'get' do %>
  <%= text_field_tag :note_search_term, params[:note_search_term]%>
  <%= submit_tag "Search" %>
<% end %>

<% if @search_results.present? %>
  <h3>Search Results</h3>
  <p>Found <%= @search_results.count%> result(s)</p>
  <% @search_results.each do |n| %>
    <p> <%= n.name %> <%= link_to "#{n.directory.full_path}", directories_path(current_id: n.directory.id) %> </p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>